# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(17161B)
$foreground = rgb(FCE9D9)
$color0 = rgb(3F3D43)
$color1 = rgb(151122)
$color2 = rgb(3F2A2D)
$color3 = rgb(4F3431)
$color4 = rgb(4F4259)
$color5 = rgb(7F5D53)
$color6 = rgb(B9916D)
$color7 = rgb(F3D8C0)
$color8 = rgb(AA9786)
$color9 = rgb(1D162E)
$color10 = rgb(55393C)
$color11 = rgb(694541)
$color12 = rgb(6A5877)
$color13 = rgb(AA7C6F)
$color14 = rgb(F7C192)
$color15 = rgb(F3D8C0)
